version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: metrics_development
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  be:
    build:
      context: ./metrics_be
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - ./metrics_be:/backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/metrics_development
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password

  fe:
    build:
      context: ./metrics_fe
    command: bash -c "rm -f tmp/pids/server.pid && yarn run dev"
    volumes:
      - ./metrics_fe:/app
    ports:
      - "3001:3000"
    depends_on:
      - be
    environment:
      REACT_APP_API_URL: http://be:3000

volumes:
  postgres_data:
